### ISSUE TITLE
MSSQL environment restore: internal server error (Status code 500) on creation of rulesets

### ISSUE THREAD

**Issue by slusardi01** [delphix/masking-initializer#1]
After a complete backup, I tried to restore a single MSSQL environment (as all our testing had been with oracle to date).  I made the necessary edits to the base.Json file to contain only the one MSSQL environment as well as the correlating application.json file to add passwords for the connectors.  

I ended up with an internal server error, status code 500  during creation of rule sets.

2018-05-01 12:35:29.600 [main] DEBUG com.delphix.masking.initializer.maskingApi.endpointCaller.ApiCallDriver - Response body: {"errorMessage":"Encountered internal server error, please see the logs for more details"}

2018-05-01 12:35:29.600 [main] ERROR com.delphix.masking.initializer.maskingApi.SetupDriver - Got status code: [500] with message [Encountered internal server error, please see the logs for more details] trying to hit URL: [http://delappdmw2.  

Attached is a tail of the All.log file:
[MSSQL_TailOfAll.log](https://github.com/delphix/masking-initializer/files/1980927/MSSQL_TailOfAll.log)
:8282/masking/api/table-metadata] [POST]

**Comment by bpg130** [comment]
@slusardi01 can you provide the masking logs at the time of these calls?

**Comment by slusardi01** [comment]
Ben, When you are requesting Masking Logs, would these be the same logs generated on the virtualization engine for support logs ??

**Comment by bpg130** [comment]
@slusardi01 yep! If you create a support bundle and then look in the `masking/logs/AppLogs/` folder, those are the logs that I am talking about.

I will send you my email address privately so that you can send me those logs directly and don't have to post them publicly.

**Comment by slusardi01** [comment]
Okay.   We have a disk issue at the moment that is impeding the creation of the logs.   As soon as that is resolved, I could work on that.

**Comment by bpg130** [comment]
@slusardi01,  no problem. When you get the disk issue figured out, please send the logs to masking-object-manager@delphix.com so we can take a look at the internal server error.

**Comment by slusardi01** [comment]
will do, thank you

**Comment by slusardi01** [comment]
I have the support bundle from the engine.  I can not email as the file is > 34MB which hits our email threshold limitation.    Do you have a location I can post/ftp the file to instead ?  Additionally,   I can not Putty to the masking engine to find the logs you seek in masking/logs/AppLogs.   Sysadmin puts you into the CLI, and I do not have my own login so I can not sudo to delphix like we do on the VM targets.   If there are other suggestions, please let me know.  Thank  you.

**Comment by bpg130** [comment]
You should be able to unpack the support bundle, and then those logs should be in the masking folder of the support bundle. If that doesn't work we can have you upload the support bundle to the same way you would for a support case.

**Comment by slusardi01** [comment]
Okay.  I will give that a try.  Thank you


Suzanne


________________________________

**Comment by slusardi01** [comment]
Resent

**Comment by slusardi01** [comment]
Uploading support bundle from masking engine through Delphix support site.

**Comment by bpg130** [comment]
I found the following in the masking logs at the time of the error noted above.
```
2018-05-01 16:35:29,600  [http-nio-8282-exec-21] ERROR c.dmsuite.common.utils.DBConnection - Error while getting sql server Connection Object
java.sql.SQLException: Login failed for user '<USER_NAME>'.
	at net.sourceforge.jtds.jdbc.SQLDiagnostic.addDiagnostic(SQLDiagnostic.java:372)
	at net.sourceforge.jtds.jdbc.TdsCore.tdsErrorToken(TdsCore.java:2820)
	at net.sourceforge.jtds.jdbc.TdsCore.nextToken(TdsCore.java:2258)
	at net.sourceforge.jtds.jdbc.TdsCore.login(TdsCore.java:603)
	at net.sourceforge.jtds.jdbc.ConnectionJDBC2.<init>(ConnectionJDBC2.java:352)
	at net.sourceforge.jtds.jdbc.ConnectionJDBC3.<init>(ConnectionJDBC3.java:50)
	at net.sourceforge.jtds.jdbc.Driver.connect(Driver.java:185)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
```
So it looks like it is failing to authenticate with your database.

Did you fill in the passwords for this backup file? See [this](https://github.com/delphix/masking-initializer/#password-limitations) section in the `README` for information on filling in the passwords. This section was accidentally removed from the `README` in a previous version, so this part of the restore process might have been overlooked.
