### ISSUE TITLE
"[DATE] [BUG]" Unable to backup masking server

### ISSUE THREAD

**Issue by akblackwel** [delphix/masking-initializer#60]
** Expected Behavior**
Backup of masking server should start

** Actual Behavior**
15:44:19.590 [main] ERROR com.delphix.masking.initializer.main - Error while running: 
java.lang.RuntimeException: Unable to make folder /mnt/delphix/08-12-2020
        at com.delphix.masking.initializer.maskingApi.BackupDriver.<init>(BackupDriver.java:161) ~[dlpx-masking-initializer-1.1.0.jar:?]
        at com.delphix.masking.initializer.main.main(main.java:17) [dlpx-masking-initializer-1.1.0.jar:?]

**Steps To Reproduce the Problem**
./dlpx-masking-initializer -f "/mnt/delphix/08-12-2020" -H host -p 80 -u USER -e -c -g -o -b -l TRACE

**Version**
1.1.0

The directory already exists. As the user in question, I can create files and directories, but the app seems to fail.

**Comment by anilsrivastava1202** [comment]
Thanks, @akblackwel  for using this tool.

**In order to backup and engine, the user must provide 5 arguments to this tool.**
1. The file in which to store the backup. -f
2. The hostname of the masking engine to back up (e.g. myMaskingEngine). -H
3. The port the masking engine is located at. -p
4. Username of an admin account for that masking engine. -u
5. Password for that admin account. -P

For example, if I wanted to store the backup file at /Users/me/backup.yaml for a masking engine located at https://companyXMasking.com:8282/dmsuite with admin user admin_user and password admin_password the following command would achieve this.

./dlpx-masking-initializer -f /Users/me/backup.yaml -H companyXMasking.com -p 8282 -u admin_user -P admin_password -b
After this operation completes, the file /Users/me/backup.yaml should contain all masking state from the host engine.

**Note:** Seems like you are missing the filename and just providing the directory name. Please try by adding backup filename as below ,
./dlpx-masking-initializer -f **/mnt/delphix/08-12-2020/backup.yaml** -H host -p 80 -u USER -e -c -g -o -b etc.

Also please make sure, you have enough permission to read/write the file inside the given directory.

**Comment by akblackwel** [comment]
I believe something else is going on here.  Still now working

./dlpx-masking-initializer -f /mnt/delphix/backup.yml -H HOST -p 80 -u USER -e -c -g -o -b -l TRACE

10:46:43.945 [main] ERROR com.delphix.masking.initializer.main - Error while running: 
java.lang.RuntimeException: Unable to make folder /mnt/delphix/backup.yml

$ touch /mnt/delphix/test.txt

ls -la /mnt/delphix/test.txt 
-rwx------. 1 usr grp 0 Aug 31 10:48 /mnt/delphix/test.txt

It seems java is having issues writing to nas.
